;============================
;NETWORK CLASS
;Generated by Casey Kerr
;============================

;============================
;PURPOSE
;	-Single Network Library
;============================

;============================
;INCLUDES
;============================
Include "Network\Server.bb"
Include "Network\Connection.bb"
Include "Network\Client.bb"

;============================
;CONSTANTS
;============================
;Net Verbs
Const NET_SET				=1
CONST NET_READ				=2
CONST NET_RUN				=3
;Net Objects
CONST NET_SERVER			=1
CONST NET_CONNECTION			=2
Const NET_CLIENT			=3
Const NET_PLAYER			=4


;============================
;GLOBALS
;============================

;============================
;ARRAYS
;============================

;============================
;OBJECT
;============================

;============================
;METHODS
;============================
Function NetworkStart()
	;Purpose: Initialize Class
	;Parameters: None
	;Return: None
	ServerStart()
	ConnectionStart()
	ClientStart()
End Function

Function NetworkStop()
	;Purpose: Shutdown Class
	;Parameters: None
	;Return: None
	ClientStop()
	ConnectionStop()
	ServerStop()
End Function

Function NetworkUpdate()
	;Purpose: Main Loop Update. Updates all Network Instances
	;Parameters: None
	;Return: None
	ServerUpdate()
	ConnectionUpdate()
	ClientUpdate()
End Function
